---
title: "week_05"
output: html_output
---

#
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(tidytuesdayR)
library(ggrepel)
library(gridExtra)
library(patchwork)
library(extrafont)
```

#
```{r}
week <- paste0("week_", "05")

dir.create(paste0("2022/codes/", week))

setwd(paste0("2022/codes/", week))

extrafont::fonts()

font <- extrafont::fonts()[78]

```

#
```{r}
#tt <- tidytuesdayR::tt_load("2022-02-01")
breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv')
trait_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/trait_description.csv')
breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv')
```


```{r}
caption.text <- "Source: American Kennel Club"
```

```{r}
top.10.2020 <- breed_rank_all %>% 
  filter(`2020 Rank` <= 10) %>% 
  select(Breed, `2020 Rank`)

breed_traits.top.10 <- breed_traits %>%
  mutate(Breed = str_squish(Breed)) %>% 
  filter(Breed %in% top.10.2020$Breed)
```

```{r}
breed_traits.top.10 <- breed_traits.top.10 %>% 
  select(-starts_with("coat")) %>% 
  pivot_longer(cols = -Breed, names_to = "traits", values_to = "value")
```

```{r}
breed_traits.top.10 <- breed_traits.top.10 %>%
  left_join(top.10.2020) %>% 
  mutate(Breed = paste0(Breed, "/ (", `2020 Rank` , ")")) %>% 
  mutate(Breed = fct_reorder(Breed, `2020 Rank`, .desc = T))


```


```{r}
color <- c("#EEE2DF", "#eed7c5", "#c89f9c", "#c97c5d", "#b36a5e")

p1 <- breed_traits.top.10 %>% 
  ggplot(aes(x= traits, y = Breed, fill = as.factor(value))) +
  geom_tile(color = "gray100", size = 1)+
  theme_minimal()+
  coord_cartesian(clip = "off")+
  scale_x_discrete(position = "top")+
  scale_fill_manual(values = color)+
  #paletteer::scale_fill_paletteer_d("dichromat::BluetoOrange_8")+
  theme_minimal(base_family = font, base_size = 15)+
  theme(axis.text.x = element_text(angle = 45, hjust = 0, 
                                   family = font),
        #axis.title.y = element_text(angle = 0, hjust = 1),
        plot.title.position = "plot",
        #plot.background = element_rect(color = NA, fill = "#FFFCF7"),
        legend.position = "bottom", legend.direction = "horizontal",
        plot.caption.position = "plot",
        plot.tag.position = "bottom",
        plot.tag = ggtext::element_markdown(),
        plot.margin = margin(1, 7, -1, 1, "cm"))+

  labs(fill = "Placement on scale", title = "Dog Breed Characteristics", 
       subtitle = "10 most popular breeds based on AKC registration statistics in 2019",
       y = "Breeeds/Rank", x = "Traits", caption = caption.text, tag = "<br>Trait table")

p1
```


```{r}
#https://stackoverflow.com/questions/68216198/grid-table-customization-of-column-header-background-color-and-font-size

#https://stackoverflow.com/questions/51957159/grid-table-plots-setting-cell-background-color-based-on-row-values

# https://stackify.dev/383759-grid-table-and-tablegrob-in-gridextra-package

table <- trait_description %>% 
  select(-Description) %>% 
  arrange(Trait) %>% 
  dplyr::rename("Trait 1" = Trait_1, "Trait 5" = Trait_5)

my_table_theme <- ttheme_default(
  base_size = 11, base_family = font,
  colhead =list(fg_params=list(col ="gray50", fontface="bold.italic"), bg_params=list(fill="#FFE5C9")),
  core=list(fg_params=list(col ="gray50"), bg_params = list(fill = c("#FFF1E0", "#FFFCF7"))))

table <- gridExtra::tableGrob(table, rows = rownames(NA), 
                              theme = my_table_theme)
```



```{r}
plot <- gridExtra::grid.arrange(p1, table, ncol = 1)


#plot <- p1 / table
  
ggsave(plot = plot, filename = paste0(week, ".png"), 
       height = 12, 
       width = 12, 
       units = "in",
       bg = "#FFFCF7")

xopen::xopen(paste0(week, ".png"))
```

